/*
 * SEI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.42
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Sei);
  }
}(this, function(expect, Sei) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Payload4', function() {
      beforeEach(function() {
        instance = new Sei.Payload4();
      });

      it('should create an instance of Payload4', function() {
        // TODO: update the code to test Payload4
        expect(instance).to.be.a(Sei.Payload4);
      });

      it('should have the property siglaSistema (base name: "siglaSistema")', function() {
        // TODO: update the code to test the property siglaSistema
        expect(instance).to.have.property('siglaSistema');
        // expect(instance.siglaSistema).to.be(expectedValueLiteral);
      });

      it('should have the property identificacaoServico (base name: "identificacaoServico")', function() {
        // TODO: update the code to test the property identificacaoServico
        expect(instance).to.have.property('identificacaoServico');
        // expect(instance.identificacaoServico).to.be(expectedValueLiteral);
      });

      it('should have the property idUnidade (base name: "idUnidade")', function() {
        // TODO: update the code to test the property idUnidade
        expect(instance).to.have.property('idUnidade');
        // expect(instance.idUnidade).to.be(expectedValueLiteral);
      });

      it('should have the property protocoloProcedimento (base name: "protocoloProcedimento")', function() {
        // TODO: update the code to test the property protocoloProcedimento
        expect(instance).to.have.property('protocoloProcedimento');
        // expect(instance.protocoloProcedimento).to.be(expectedValueLiteral);
      });

    });
  });

}));
