/*
 * SEI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.42
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Sei) {
      root.Sei = {};
    }
    root.Sei.Payload = factory(root.Sei.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Payload model module.
   * @module model/Payload
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Payload</code>.
   * @alias module:model/Payload
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Payload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Payload} obj Optional instance to populate.
   * @return {module:model/Payload} The populated <code>Payload</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('siglaSistema'))
        obj.siglaSistema = ApiClient.convertToType(data['siglaSistema'], 'String');
      if (data.hasOwnProperty('identificacaoServico'))
        obj.identificacaoServico = ApiClient.convertToType(data['identificacaoServico'], 'String');
      if (data.hasOwnProperty('idUnidade'))
        obj.idUnidade = ApiClient.convertToType(data['idUnidade'], 'String');
      if (data.hasOwnProperty('idTipoProcedimento'))
        obj.idTipoProcedimento = ApiClient.convertToType(data['idTipoProcedimento'], 'String');
      if (data.hasOwnProperty('nivelAcesso'))
        obj.nivelAcesso = ApiClient.convertToType(data['nivelAcesso'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} siglaSistema
   */
  exports.prototype.siglaSistema = undefined;

  /**
   * @member {String} identificacaoServico
   */
  exports.prototype.identificacaoServico = undefined;

  /**
   * @member {String} idUnidade
   */
  exports.prototype.idUnidade = undefined;

  /**
   * @member {String} idTipoProcedimento
   */
  exports.prototype.idTipoProcedimento = undefined;

  /**
   * @member {String} nivelAcesso
   */
  exports.prototype.nivelAcesso = undefined;


  return exports;
}));
